hyperparameters:
  min_anchor_size:
    type: double
    maxval: 0.2
    minval: 0.02
  max_anchor_size:
    type: double
    maxval: 0.6
    minval: 0.4
searcher:
  name: adaptive_asha
  metric: loss
  max_length:
    batches: 3000
  smaller_is_better: true
  max_trials: 250
