name: SSD::Standard-Test
description: VGG16-Model on Lizard-Dataset - Test Small Sizes
hyperparameters:
  aug_norm: false
  aug_rotate: true
  aug_flip: true
  backbone_arch: vgg16
  dataset: lizard
  dataset_split_size: 0.8
  enable_class_metrics: false
  force_one_class: false
  global_batch_size: 32
  hnm_norm_per_batch: true
  ignore_classes: '0,4'
  image_prediction_max_images: 5
  image_prediction_score_threshold: 0.2
  image_size: 300
  image_stride:
    type: double
    maxval: 0.8
    minval: 0.2
  l2_regularization: 0.00001
  learning_rate:
    type: log
    base: 2
    maxval: -5
    minval: -7
  max_anchor_size:
    type: double
    maxval: 0.6
    minval: 0.5
  min_anchor_size:
    type: double
    maxval: 0.08
    minval: 0.02
  momentum:
    type: const
    val: 0.9
  negative_ratio:
    type: double
    maxval: 5
    minval: 0.5
  num_workers: 16
  optimizer: sgd
  pretrained: true
  shuffle_validation: true
  use_clock: false
  use_smooth_l1: true
  warmup_batches: 300
workspace: MastersthesisBruno
project: SSD
max_restarts: 0
min_validation_period:
  batches: 300
reproducibility:
  experiment_seed: 1658162417
resources:
  agent_label: dt-cluster
  max_slots: 6
  slots_per_trial: 1
searcher:
  max_length:
    batches: 3000
  max_trials: 36
  metric: loss
  name: random
  smaller_is_better: true
entrypoint: default_trial:DefaultTrial
environment:
  image:
    cpu: deepprojects/determined-pytorch-1.12-cpu:1.0.1
    cuda: deepprojects/determined-cuda-113-pytorch-1.12-gpu:1.0.0
bind_mounts:
  - container_path: /data/ldap/histopathologic
    host_path: /data/ldap/histopathologic
    propagation: rprivate
    read_only: true
checkpoint_storage:
  save_experiment_best: 0
  save_trial_best: 0
  save_trial_latest: 0
