name: SSD::Standard-Test::TinySSD
description: "Test SSD Banana-Dataset"
hyperparameters:
  global_batch_size: 64
  dataset: "banana"
  dataset_split_size: 0.8
  num_workers: 8
  backbone_arch: "vgg16"  # TODO
  optimizer: "sgd"
  learning_rate: 0.001  # TODO
    # type: log
    # maxval: -1
    # minval: -5
    # base: 10
    # count: 8
  l2_regularization: 1e-5
  momentum: 0.9  # TODO
  image_prediction_score_threshold: 0.4
  image_prediction_max_images: 5
  image_size: 300  # TODO
  negative_ratio: 3.0
min_validation_period:
  batches: 200
searcher:
  name: grid
  metric: map
  max_length:
    batches: 3000
  smaller_is_better: true
entrypoint: default_trial:DefaultTrial
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.12-cpu:1.0.1"
    gpu: "deepprojects/determined-cuda-113-pytorch-1.12-gpu:1.0.0"
bind_mounts:
  - host_path: "/data/ldap/histopathologic"
    container_path: "/data/ldap/histopathologic"
    read_only: true
  # logging
checkpoint_storage:
  save_trial_best: 0
  save_trial_latest: 0
  save_experiment_best: 0
max_restarts: 0
resources:
  agent_label: pepper-cluster
  max_slots: 4
  slots_per_trial: 1
reproducibility:
  experiment_seed: 1658162417
