name: SSD::Standard-Test::VGG16SSD
description: "Test Anchor Sizes"
hyperparameters:
  global_batch_size: 64
  dataset: "banana"
  dataset_split_size: 0.8
  num_workers: 8
  backbone_arch: "vgg16"  # TODO
  optimizer: "sgd"
  learning_rate: 0.3  # TODO
  l2_regularization: 1e-5
  momentum: 0.9  # TODO
  hnm_norm_per_batch: true
  image_prediction_score_threshold: 0.4
  image_prediction_max_images: 5
  image_size: 300  # TODO
  negative_ratio: 3.0
  min_anchor_size:
    type: double
    minval: 0.07
    maxval: 0.35
  max_anchor_size:
    type: double
    minval: 0.6
    maxval: 1.2
min_validation_period:
  batches: 200
searcher:
  name: adaptive_asha
  metric: loss
  max_length:
    batches: 3000
  smaller_is_better: true
  max_trials: 250
  max_concurrent_trials: 8
entrypoint: default_trial:DefaultTrial
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.12-cpu:1.0.1"
    gpu: "deepprojects/determined-cuda-113-pytorch-1.12-gpu:1.0.0"
bind_mounts:
  - host_path: "/data/ldap/histopathologic"
    container_path: "/data/ldap/histopathologic"
    read_only: true
  # logging
checkpoint_storage:
  save_trial_best: 0
  save_trial_latest: 0
  save_experiment_best: 0
max_restarts: 0
resources:
  agent_label: pepper-cluster
  max_slots: 8
  slots_per_trial: 1
reproducibility:
  experiment_seed: 1658162417
