variables:
  description:
    action: "iou_match_threshold"
hyperparameters:
  iou_match_threshold:
    type: double
    minval: 0.2
    maxval: 0.8
  bbox_loss_scale: 20.0  # lower bbox_loss_scale to prevent nan loss
