variables:
  description:
    action: "Test Sizes"
hyperparameters:
  min_anchor_size:
    type: double
    maxval: 0.2
    minval: 0.02
  max_anchor_size:
    type: double
    maxval: 0.6
    minval: 0.4
