variables:
  description:
    action: "Test Small Sizes"
hyperparameters:
  min_anchor_size:
    type: double
    maxval: 0.08
    minval: 0.02
  max_anchor_size:
    type: double
    maxval: 0.6
    minval: 0.5
