variables:
  description:
    action: "anchor sizes"
hyperparameters:
  min_anchor_size:
    type: double
    maxval: 0.2
    minval: 0.02
  max_anchor_size:
    type: double
    maxval: 0.7
    minval: 0.4
