variables:
  description:
    action: "Test Small Medium"
hyperparameters:
  min_anchor_size:
    type: double
    maxval: 0.1
    minval: 0.015
  max_anchor_size:
    type: double
    maxval: 0.7
    minval: 0.4
